# Incorporate IMG changes into Mesa

FILESEXTRAPATHS:append := "${THISDIR}/mesa-pvr/${PV}:"

SRC_URI += "file://0001-Add-PVR-Gallium-driver.patch"
SRC_URI += "file://0002-dri-Add-some-new-DRI-formats-and-fourccs.patch"
SRC_URI += "file://0003-GL_EXT_sparse_texture-entry-points.patch"
SRC_URI += "file://0004-Add-support-for-various-GLES-extensions.patch"
SRC_URI += "file://0005-Add-EGL_IMG_cl_image-extension.patch"
SRC_URI += "file://0006-egl-optimise-eglMakeCurrent-for-the-case-where-nothi.patch"
SRC_URI += "file://0007-GL_EXT_shader_pixel_local_storage2-entry-points.patch"
SRC_URI += "file://0008-GL_IMG_framebuffer_downsample-entry-points.patch"
SRC_URI += "file://0009-GL_OVR_multiview-entry-points.patch"
SRC_URI += "file://0010-Add-OVR_multiview_multisampled_render_to_texture.patch"
SRC_URI += "file://0011-wayland-drm-install-wayland-drm.xml-to-the-configure.patch"
SRC_URI += "file://0012-Enable-buffer-sharing-in-the-kms_swrast-driver.patch"
SRC_URI += "file://0013-egl-wayland-add-support-for-RGB565-back-buffers.patch"
SRC_URI += "file://0014-egl-wayland-post-maximum-damage-when-blitting.patch"
SRC_URI += "file://0015-egl-wayland-flush-the-drawable-before-blitting.patch"
SRC_URI += "file://0016-dri-use-a-supported-API-in-driCreateNewContext.patch"
SRC_URI += "file://0017-gbm-add-gbm_bo_blit.patch"
SRC_URI += "file://0018-gbm-don-t-assert-if-DRI-context-creation-fails.patch"
SRC_URI += "file://0019-egl-wayland-add-pbuffer-support.patch"
SRC_URI += "file://0020-egl-eglBindAPI-workaround-for-dEQP-bug.patch"
SRC_URI += "file://0021-GL_EXT_multi_draw_indirect-entry-points.patch"
SRC_URI += "file://0022-dri-add-support-for-YUV-DRI-config.patch"
SRC_URI += "file://0023-egl-add-support-for-EXT_yuv_surface.patch"
SRC_URI += "file://0024-dri-add-missing-__DRI_IMAGE_COMPONENTS-define-for-EG.patch"
SRC_URI += "file://0025-egl-wayland-expose-EXT_yuv_surface-support.patch"
SRC_URI += "file://0026-gbm-add-some-new-GBM-formats.patch"
SRC_URI += "file://0027-egl-add-null-platform.patch"
SRC_URI += "file://0028-egl-add-support-for-EXT_image_gl_colorspace.patch"
SRC_URI += "file://0029-meson-force-C-2011-for-thread_local.patch"
SRC_URI += "file://0030-dri2-add-support-for-swap-intervals-other-than-1.patch"
SRC_URI += "file://0031-null_platform-add-support-for-explicit-synchronisati.patch"
SRC_URI += "file://0032-egl-null-add-support-for-DRM-image-format-modifiers.patch"
SRC_URI += "file://0033-egl-query-the-supported-ES2-context-version.patch"
SRC_URI += "file://0034-meson-allow-libGL-to-be-built-without-GLX.patch"
SRC_URI += "file://0035-egl-wayland-process-non-resized-window-movement.patch"
SRC_URI += "file://0036-Separate-EXT_framebuffer_object-from-ARB-version.patch"
SRC_URI += "file://0037-egl-null-add-support-for-async-flip-with-front-buffe.patch"
SRC_URI += "file://0038-gbm-add-pbuffer-support.patch"
SRC_URI += "file://0039-egl-null-expose-EXT_yuv_surface-support.patch"
SRC_URI += "file://0040-dri-preserve-the-original-FD-for-driver-use.patch"
SRC_URI += "file://0041-egl-wayland-a-linear-buffer-is-not-needed-with-DRM-f.patch"
SRC_URI += "file://0042-dri3-a-linear-buffer-is-not-needed-with-DRM-format-m.patch"
SRC_URI += "file://0043-egl-drm-add-support-for-DRI_PRIME-GPU-selection.patch"
SRC_URI += "file://0044-egl-null-add-support-for-DRI_PRIME-GPU-selection.patch"
SRC_URI += "file://0045-egl-null-introduce-NULL_DRM_DISPLAY.patch"
SRC_URI += "file://0046-vulkan-wsi-check-the-DRI3-and-Present-XCB-reply-poin.patch"
SRC_URI += "file://0047-vulkan-wsi-make-the-display-FD-available.patch"
SRC_URI += "file://0048-pvr-wsi-add-PowerVR-Vulkan-WSI-library.patch"
SRC_URI += "file://0049-vulkan-wsi-Disable-use-of-VK_EXT_pci_bus_info.patch"
SRC_URI += "file://0050-vulkan-wsi-default-to-force_bgra8_unorm_first-true.patch"
SRC_URI += "file://0051-vulkan-wsi-enable-additional-formats-for-Display.patch"
SRC_URI += "file://0052-mesa-partially-revert-pbuffer-attribute-removal.patch"
SRC_URI += "file://0053-egl_dri2-set-pbuffer-config-attribs-to-0-for-non-pbu.patch"
SRC_URI += "file://0054-GL_ARB_geometry_shader4-entry-points.patch"
SRC_URI += "file://0055-egl-wayland-add-EGL_BUFFER_PRESERVED-support.patch"
SRC_URI += "file://0056-glapi-restore-exec-dynamic.patch"
SRC_URI += "file://0057-Revert-meson-check-mtls-if-has_exe_wrapper.patch"
SRC_URI += "file://0058-vulkan-wsi-extend-PVR-WSI-library-to-destroy-surface.patch"
SRC_URI += "file://0059-vulkan-wsi-dEQP-wayland.swapchain.simulate_oom.min_i.patch"
SRC_URI += "file://0060-vulkan-wsi-wayland-allocate-memory-for-swapchain-mod.patch"
SRC_URI += "file://0061-zink-remove-descriptor-mode-selection-infrastructure.patch"
SRC_URI += "file://0062-aux-draw-vectorize-aaline-computations.patch"
SRC_URI += "file://0063-gallium-draw-properly-fix-short-aalines.patch"
SRC_URI += "file://0064-gallium-draw-do-not-use-trig-to-compute-tangent.patch"
SRC_URI += "file://0065-mesa-support-dummy-queries-for-ARB_pipeline_statisti.patch"
SRC_URI += "file://0066-mesa-do-not-require-optional-queries.patch"
SRC_URI += "file://0067-docs-zink-update-query-requirements.patch"
SRC_URI += "file://0068-nir-Add-helper-to-create-passthrough-GS-shader.patch"
SRC_URI += "file://0069-zink-setup-driver-workaround-for-missing-linestipple.patch"
SRC_URI += "file://0070-zink-add-line-stippling-lowering-passes.patch"
SRC_URI += "file://0071-zink-emit-vars-with-nir_var_shader_temp-mode.patch"
SRC_URI += "file://0072-zink-give-gs-its-own-shader-key.patch"
SRC_URI += "file://0073-zink-process-non-optimal-key-passes-first.patch"
SRC_URI += "file://0074-zink-allow-to-generate-any-vertex-shader-stage.patch"
SRC_URI += "file://0075-zink-lower-line-stipple.patch"
SRC_URI += "file://0076-zink-do-not-complain-about-missing-line-stipple-supp.patch"
SRC_URI += "file://0077-util-dynarray-Add-an-append_array-helper.patch"
SRC_URI += "file://0078-zink-do-not-lower-gs-intrinsics.patch"
SRC_URI += "file://0079-zink-do-not-lower-gs-intrinscs-take-two.patch"
SRC_URI += "file://0080-zink-add-gl_point-lowering-pass.patch"
SRC_URI += "file://0081-zink-rename-zink_set_line_stipple_keys.patch"
SRC_URI += "file://0082-zink-add-driver-workaround-for-missing-gl_point_size.patch"
SRC_URI += "file://0083-zink-fix-rebase-mistake.patch"
SRC_URI += "file://0084-zink-do-not-leave-needless-shader-temps-around.patch"
SRC_URI += "file://0085-zink-Don-t-set-dynamic-color-attachment-state-for-0-.patch"
SRC_URI += "file://0086-zink-fix-line-stipple-varying-allocation.patch"
SRC_URI += "file://0087-zink-add-line-smooth-lowering-passes.patch"
SRC_URI += "file://0088-zink-lower-smooth-lines-if-not-supported.patch"
SRC_URI += "file://0089-zink-fix-line-smooth-interpolation.patch"
SRC_URI += "file://0090-zink-Only-expose-PIPE_CAP_IMAGE_ATOMIC_FLOAT_ADD-if-.patch"
SRC_URI += "file://0091-zink-Only-expose-PIPE_CAP_SHADER_ATOMIC_INT64-if-we-.patch"
SRC_URI += "file://0092-ci-Fix-VK-driver-setup-for-HWCI_START_.patch"
SRC_URI += "file://0093-docs-gallium-Explain-that-MSAA-transfer_map-must-be-.patch"
SRC_URI += "file://0094-u_transfer_helpre-Drop-interleave-handling-from-the-.patch"
SRC_URI += "file://0095-u_transfer_helper-Use-common-code-for-interleaved-un.patch"
SRC_URI += "file://0096-u_transfer_helper-Merge-in-place-and-split-z-s-inter.patch"
SRC_URI += "file://0097-zink-Have-u_transfer_helper-resolve-MSAA-surfaces-wh.patch"
SRC_URI += "file://0098-zink-Add-an-assert-for-not-seeing-any-more-MSAA-imag.patch"
SRC_URI += "file://0099-zink-fix-disappearing-smooth-lines-after-workaround.patch"
SRC_URI += "file://0100-zink-split-out-swapchain-render-update-fixups-into-s.patch"
SRC_URI += "file://0101-zink-catch-a-potential-corner-case-with-dynamic-rend.patch"
SRC_URI += "file://0102-zink-re-clamp-dynamic-render-area-when-doing-swapcha.patch"
SRC_URI += "file://0103-zink-add-a-bunch-of-asserts-for-starting-dynamic-ren.patch"
SRC_URI += "file://0104-zink-delete-dead-code.patch"
SRC_URI += "file://0105-zink-only-flag-modules_changed-in-optimal-path-if-a-.patch"
SRC_URI += "file://0106-zink-put-line-emulation-stuff-behind-optimal_keys-ch.patch"
SRC_URI += "file://0107-zink-simplify-some-depth-texturing-spv.patch"
SRC_URI += "file://0108-zink-fix-some-weird-indentation-in-zink_set_sampler_.patch"
SRC_URI += "file://0109-zink-unify-some-shadow-tex-code-in-match_tex_dests_i.patch"
SRC_URI += "file://0110-zink-use-optimal-key-for-pipeline-library-hash.patch"
SRC_URI += "file://0111-zink-add-a-fs-base-key-fix-optimal-fs-key-packing.patch"
SRC_URI += "file://0112-zink-add-a-condition-to-needs_write_s.patch"
SRC_URI += "file://0113-zink-fix-the-stencil-write.patch"
SRC_URI += "file://0114-gallium-draw-use-nir_shader_instructions_pass-for-ni.patch"
SRC_URI += "file://0115-gallium-draw-assert-shader-stage.patch"
SRC_URI += "file://0116-gallium-draw-support-lowering-stipple-smooth.patch"
SRC_URI += "file://0117-zink-lower-stipple-smooth.patch"
SRC_URI += "file://0118-zink-prune-old-swapchains-on-present.patch"
SRC_URI += "file://0119-zink-whitespace-fixup.patch"
SRC_URI += "file://0120-zink-remove-depth_clip_control_missing-workaround.patch"
SRC_URI += "file://0121-zink-add-a-util-function-for-creating-semaphores.patch"
SRC_URI += "file://0122-zink-add-a-binary-semaphore-cache.patch"
SRC_URI += "file://0123-zink-move-semaphore-caching-to-zink_reset_batch_stat.patch"
SRC_URI += "file://0124-zink-consolidate-semaphore-creation-where-possible.patch"
SRC_URI += "file://0125-zink-simplify-some-dynarray-concat-descriptor-code.patch"
SRC_URI += "file://0126-zink-add-pass-checking-for-lod-overflow-in-txf.patch"
SRC_URI += "file://0127-zink-add-zink_cs_key.patch"
SRC_URI += "file://0128-zink-add-VK_EXT_image_robustness.patch"
SRC_URI += "file://0129-zink-add-robust_access-field-to-shader-key.patch"
SRC_URI += "file://0130-zink-lower-LOD-invalid-txf-when-imageRobustAccess2-i.patch"
SRC_URI += "file://0131-zink-update-gl43-profile-to-allow-imageRobustAccess.patch"
SRC_URI += "file://0132-zink-flag-old-style-shadow-tex-mask-for-fragment-sha.patch"
SRC_URI += "file://0133-zink-break-out-tex-dest-rewriting-into-separate-func.patch"
SRC_URI += "file://0134-zink-add-an-extra_data-param-to-zink_shader_compile.patch"
SRC_URI += "file://0135-zink-track-depth-swizzle-on-samplerviews.patch"
SRC_URI += "file://0136-zink-add-a-fs-shader-key-member-to-indicate-depth-te.patch"
SRC_URI += "file://0137-zink-rework-depth-sampler-splatting-in-shaders.patch"
SRC_URI += "file://0138-zink-block-pipeline-fast-pathing-for-any-programs-us.patch"
SRC_URI += "file://0139-zink-plug-in-the-program-module-parts-of-shadow-text.patch"
SRC_URI += "file://0140-zink-create-another-samplerview-for-shadow-textures.patch"
SRC_URI += "file://0141-zink-remove-old-depth-swizzle-workaround.patch"
SRC_URI += "file://0142-zink-pass-depth-swizzle-data-block-to-shader-compile.patch"
SRC_URI += "file://0143-zink-reorder-commands-more-aggressively.patch"
SRC_URI += "file://0144-zink-relax-bresenhamLines-requirement-for-non-strict.patch"
SRC_URI += "file://0145-zink-set-PIPE_CAP_SURFACE_REINTERPRET_BLOCKS.patch"
SRC_URI += "file://0146-zink-ralloc-zink_shader-structs.patch"
SRC_URI += "file://0147-zink-fix-compute-shader-leaks.patch"
SRC_URI += "file://0148-zink-allocate-program-shader-caches-from-the-program.patch"
SRC_URI += "file://0149-zink-free-resource-objects-views-array-during-destru.patch"
SRC_URI += "file://0150-zink-fix-indentation-of-rebind_image.patch"
SRC_URI += "file://0151-zink-only-try-for-a-fb-rebind-if-fb-binds-exist-in-r.patch"
SRC_URI += "file://0152-zink-account-for-null-surface-when-trying-to-retain-.patch"
SRC_URI += "file://0153-zink-break-out-pipe_surface-init-for-new-surface-cre.patch"
SRC_URI += "file://0154-zink-const-ify-a-surface-param.patch"
SRC_URI += "file://0155-zink-don-t-handle-mutable-init-on-surface-creation-w.patch"
SRC_URI += "file://0156-zink-verify-compressed-format-layer-count-when-creat.patch"
SRC_URI += "file://0157-Kopper-Fix-unsupport-DRM-format-modifier-being-intre.patch"
SRC_URI += "file://0158-zink-fix-incorrect-line-mode-check-for-bresenham.patch"
SRC_URI += "file://0159-zink-disable-implicit_sync-for-IMG-driver.patch"
SRC_URI += "file://0160-zink-fix-shadow-mask-change-logic-when-binding-sampl.patch"
SRC_URI += "file://0161-zink-track-shadow-swizzle-for-all-shader-stages.patch"
SRC_URI += "file://0162-zink-minor-formatting-change.patch"
SRC_URI += "file://0163-zink-add-needs_zs_shader_swizzle-shader-key.patch"
SRC_URI += "file://0164-zink-extend-shadow-swizzle-pass-to-all-zs-textures.patch"
SRC_URI += "file://0165-zink-add-depth-stencil-needs-shader-swizzle-workarou.patch"
SRC_URI += "file://0166-zink-workaround-undefined-swizzle-1-for-z-s-textures.patch"
SRC_URI += "file://0167-zink-rename-shadow-key-to-zs-swizzle.patch"
SRC_URI += "file://0168-kopper-add-compatibility-to-old-style-DRI-interface.patch"

# Some files are stored in the GIT repository with LF line endings,
# but have CR/LF line endings when checked out. Patches generated for
# such files with "git format-patch" have LF line endings, which
# cannot be applied, without error, to checked out files with "patch".
# The line endings for such files are converted from CR/LF to LF prior
# to patching, and converted back afterwards.
PATCH_CRLF_FILES = "src/mesa/main/formats.csv"

crlf_file_prepatch() {
	local rf
	local af

	for rf in "${PATCH_CRLF_FILES}"
	do
		af=${S}/${rf}
		sed 's/\r$//' < ${af} > ${af}.lf && mv -f ${af}.lf ${af}
	done
}

crlf_file_postpatch() {
	local rf
	local af
	for rf in "${PATCH_CRLF_FILES}"
	do
		af=${S}/${rf}
		sed 's/$/\r/' < ${af} > ${af}.crlf && mv -f ${af}.crlf ${af}
	done
}

do_patch[prefuncs] += "crlf_file_prepatch"
do_patch[postfuncs] += "crlf_file_postpatch"

PACKAGECONFIG:append:class-target = " pvr-alias"

GALLIUMDRIVERS:append:class-target = ",pvr"

PVR_DRM_MODESET_DRIVER_NAME = "synaptics"

PACKAGECONFIG[pvr-alias] = "-Dgallium-pvr-alias=${PVR_DRM_MODESET_DRIVER_NAME}"

# The DDK integration example uses the virtio-gpu display driver, which
# would normally be associated with the virgl GPU driver.
PACKAGECONFIG:remove = "virgl"

VULKAN_DRIVERS:append:class-target = ",pvr"

FILES:mesa-vulkan-drivers:append = " ${libdir}/libpvr_mesa_wsi.so"

FILES:libegl-mesa-dev:append = "${@bb.utils.contains('DISTRO_FEATURES', 'wayland', ' ${datadir}/pkgconfig/wayland-drm.pc', '', d)}"
